---
- name: home folders
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop: "{{ base_home_folders }}"

- name: additional folders
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop: "{{ additional_folders }}"
  when: additional_folders
