---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if bin exists
      block:
        - name: stat bin
          ansible.builtin.stat:
            path: "{{ ansible_user_dir }}/bin"
          register: bin

        - name: bin exists
          ansible.builtin.assert:
            that: bin.stat.exists
